# Generated by Django 3.0.6 on 2021-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
